export enum UserRole {
  ADMIN = 'ADMIN',
  PROVIDER = 'PROVIDER',
  NAVIGATOR = 'NAVIGATOR',
  PATIENT = 'PATIENT',
}

export enum ConversationPhase {
  DISCLAIMER = 'DISCLAIMER',
  PATIENT_CONTEXT = 'PATIENT_CONTEXT',
  EMERGENCY_CHECK = 'EMERGENCY_CHECK',
  SYMPTOM_SELECTION = 'SYMPTOM_SELECTION',
  SCREENING = 'SCREENING',
  FOLLOW_UP = 'FOLLOW_UP',
  BRANCHED = 'BRANCHED',
  SUMMARY = 'SUMMARY',
  ADDING_NOTES = 'ADDING_NOTES',
  COMPLETED = 'COMPLETED',
  EMERGENCY = 'EMERGENCY',
}

export enum TriageLevel {
  CALL_911 = 'CALL_911',
  URGENT = 'URGENT',
  NOTIFY_CARE_TEAM = 'NOTIFY_CARE_TEAM',
  NONE = 'NONE',
}

export enum SeverityLevel {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
}

export enum MessageType {
  TEXT = 'TEXT',
  OPTION_SELECT = 'OPTION_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  DATE_PICK = 'DATE_PICK',
  NUMBER_INPUT = 'NUMBER_INPUT',
  SUMMARY = 'SUMMARY',
}

export enum MessageRole {
  BOT = 'BOT',
  PATIENT = 'PATIENT',
}

